# Generated by Django 3.2.7 on 2022-08-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('original', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='like_users',
            field=models.ManyToManyField(related_name='like_originals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='original',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='originals', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OriginalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_users', models.ManyToManyField(related_name='like_original_comments', to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='original.original')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
